CREATE TABLE IF NOT EXISTS proveedores (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nit_cc VARCHAR(50) NOT NULL,
  razon_social VARCHAR(200) NOT NULL,
  tipo_persona ENUM('natural', 'juridica') NOT NULL,
  origen ENUM('nacional', 'extranjera') NOT NULL,
  clasificacion ENUM('productos', 'servicios', 'ambos') NOT NULL,
  contacto_comercial_nombre VARCHAR(150) NULL,
  contacto_comercial_telefono VARCHAR(50) NULL,
  contacto_comercial_email VARCHAR(150) NULL,
  contacto_pagos_nombre VARCHAR(150) NULL,
  contacto_pagos_telefono VARCHAR(50) NULL,
  contacto_pagos_email VARCHAR(150) NULL,
  contacto_tecnico_nombre VARCHAR(150) NULL,
  contacto_tecnico_telefono VARCHAR(50) NULL,
  contacto_tecnico_email VARCHAR(150) NULL,
  documentacion_estado JSON NULL,
  calificacion_actual DECIMAL(5, 2) NULL,
  created_by INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_proveedores_nit_cc (nit_cc),
  CONSTRAINT fk_proveedores_created_by FOREIGN KEY (created_by) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
